### ISSUE TITLE
[Question] Is denyUpdate collection-scoped or field-scoped ?

### ISSUE THREAD

**Issue by gaillota** [aldeed/meteor-schema-deny#2]
Hello,

Let's say I have a schema containing a field `deletedAt`
```
deletedAt: {
    type: Date,
    optional: true,
    denyUpdate: true
}
```

If I try to set the `deletedAt ` field on my document with an `update` operation on my collection, will this fail ?

In other words, does the denyUpdate prevent the alteration of a field using an `update` operation, no matter what (which means you can only set it during the `insert`) ? Or does it mean you can only set it **once** (and not update it later), even with an `update `operation.

Hope I was clear enough.

**Comment by copleykj** [comment]
This means that your deletedAt field would only be allowed in an insert.
